### ISSUE TITLE
Change color of border

### ISSUE THREAD

**Issue by martinyis** [martinyis/PrepAi#1]
The color of the border is white right now. We are using TextField from MUI so I guess it is the default color. 
It needs to be changed to this color '#0f5263'

FIlePath: Prep-ai\client\src\modules\InfoPanel.jsx

Image: 

![image](https://user-images.githubusercontent.com/97173732/228640944-ca1b3f42-2608-4a71-9fbc-fb3ef42c042b.png)

**Comment by PUJAmangale1221** [comment]
Hey Maintainers, I would like to resolve this issue could you please assign me to this issue...!!

**Comment by PUJAmangale1221** [comment]
Thank you for assigning me, can I look into this after a few days since my
exams are going to start. I was setting the environment but  Node.Js is
throwing some issues. So first I need to resolve it.
I hope you understand

Thank you,
Puja Mangale
