### ISSUE TITLE
Fix Link In CreateButton.jsx

### ISSUE THREAD

**Issue by martinyis** [martinyis/PrepAi#10]
The Links which wraps up a button needs to navigate to createPrep page when clicked but it does not do so. Needs to be fixed

**Comment by martinyis** [comment]
> Hey! I know how to solve this, so can you assign this issue to me?

Thank you for your interest @3simransharma. Go ahead!

**Comment by 3simransharma** [comment]
I have tried to solve the issue; from my side it is working. I have used useNavigate() on Button's OnClick event. My PR is : [PR](https://github.com/martinyis/PrepAi/pull/14)
