### ISSUE TITLE
Exposed Key

### ISSUE THREAD

**Issue by GabrielMurry** [martinyis/PrepAi#11]
Just a reminder that in your 'index.js' file within 'server' directory, you have an exposed openAI API key. Your '.env' file contains that key but you are not importing that key from your '.env' file into your 'index.js' file. Install and configure 'dotenv', import the variable through 'process.env.OPENAI_API_KEY', and add '.env' to your '.gitignore' file so it doesn't show up on github.

Hope this helps!

**Comment by martinyis** [comment]
> Just a reminder that in your 'index.js' file within 'server' directory, you have an exposed openAI API key. Your '.env' file contains that key but you are not importing that key from your '.env' file into your 'index.js' file. Install and configure 'dotenv', import the variable through 'process.env.OPENAI_API_KEY', and add '.env' to your '.gitignore' file so it doesn't show up on github.
> 
> Hope this helps!

@KalebArmbrust Thank you for your issue! It is a good point! Feel free to make more issues if you see any on the website.

**Comment by GabrielMurry** [comment]
No problem! Will do!

**Comment by martinyis** [comment]
> No problem! Will do!

Hey @GabrielMurry  if you have time I would really appreciate you to fix this issue because I have problems with this

**Comment by GabrielMurry** [comment]
Yea of course! I'll fork the repo and see what I can do, then send you a pull request when I'm done
