### ISSUE TITLE
TextFields in InfoPanel module should be limited to 50 characters

### ISSUE THREAD

**Issue by martinyis** [martinyis/PrepAi#15]
Description
Currently, the TextFields located in the InfoPanel module do not have any character limit, which can cause issues with formatting and readability. To improve user experience, we should limit the number of characters that can be entered in these TextFields to 50 characters.

Proposed Solution
To implement this change, we should add a character limit of 50 to the TextFields in the InfoPanel module. This will ensure that users are unable to type more than 50 characters into the TextFields, thus preventing any formatting or readability issues.

Additional Information
This change should be tested thoroughly to ensure that it does not cause any unintended consequences.

![image](https://user-images.githubusercontent.com/97173732/231589287-5e64683e-8948-40da-8a4f-59eb1c6ddcd9.png)

**Comment by AnshulKahar2729** [comment]
@martinyis that can be easily done using javascript, assign me the issue so that I can solve this issue and make a PR.

**Comment by martinyis** [comment]
> @martinyis that can be easily done using javascript, assign me the issue so that I can solve this issue and make a PR.
@AnshulKahar2729  Thank you for your interest. Go ahead!

**Comment by AnshulKahar2729** [comment]
Ok so when character exceeds the count, do you want to add the toast or do you want to have HTML text exactly below that input field in the typical red error color which will show that count of character has been exceed.

**Comment by martinyis** [comment]
> Ok so when character exceeds the count, do you want to add the toast or do you want to have HTML text exactly below that input field in the typical red error color which will show that count of character has been exceed.

I think the red color text would work better.

**Comment by AnshulKahar2729** [comment]
I have made a PR see if it's work for you.

**Comment by Sky-De** [comment]
as it is mui TextField we can esaily use inputProps={{ maxLength: 12 }} on these two TextField,
i will fix and pull it
