### ISSUE TITLE
Limiting character count for TextareaAutosize

### ISSUE THREAD

**Issue by martinyis** [martinyis/PrepAi#16]
Description
The current implementation of TextareaAutosize for notes and additional information does not have any character limits, which can cause issues with formatting and readability. To improve user experience, we should limit the number of characters that can be entered in these fields.

Proposed Solution
To implement this change, we should add character limits to the TextareaAutosize fields for notes and additional information. The TextareaAutosize for notes should accept a maximum of 3000 characters, while the TextareaAutosize for additional information should accept a maximum of 1000 characters.

Additional Information
This change should be tested thoroughly to ensure that it does not cause any unintended consequences. We should also update any relevant documentation or user guides to reflect these new character limits. Finally, we should consider adding appropriate error messages or notifications to inform the user when they have exceeded the character limit.
![image](https://user-images.githubusercontent.com/97173732/231589936-6bc8bffe-6b19-4c92-b268-9adca7612ce8.png)

**Comment by pravinargade18** [comment]
Hey @martinyis,  I'll be working on this issue and will send you PR.

**Comment by martinyis** [comment]
Nice job! Merged to main!
