### ISSUE TITLE
Redirecting from StartButton.jsx to ResultPage.jsx

### ISSUE THREAD

**Issue by martinyis** [martinyis/PrepAi#17]
Description
Currently, clicking on the Start button in StartButton.jsx does not redirect the user to the ResultPage.jsx. To improve user experience, we should modify the StartButton.jsx so that it redirects the user to the ResultPage.jsx when clicked.

![image](https://user-images.githubusercontent.com/97173732/231590192-a2f75bef-a4e0-4b71-afc4-4cfb27031d83.png)

**Comment by GabrielMurry** [comment]
Hey Martin! I decided to tackle this issue, hope that's ok, I can send a PR.
