### ISSUE TITLE
Incorrect Background Color for Mobile Navbar on GitHub Project

### ISSUE THREAD

**Issue by martinyis** [martinyis/PrepAi#23]
We have identified an issue with the background color of the mobile navbar on the GitHub project. Currently, the background color is set to an incorrect value of white, whereas it should be set to "rgb(12, 51, 52, 1)" to match the project's color scheme.

This inconsistency can be confusing for users and negatively impact their experience. Therefore, we urge the development team to prioritize this issue and make the necessary changes as soon as possible.

We suggest testing the updated color scheme thoroughly to ensure it works well with the project's overall design. Once the changes have been made, please confirm that the mobile navbar background color is set to "rgb(12, 51, 52, 1)"
![image](https://user-images.githubusercontent.com/97173732/231916620-c459954a-cfb3-4a14-b15e-6eb5535afa90.png)

**Comment by dcryptoniun** [comment]
hey @martinyis, I can fix this. Please assign this to me.
