### ISSUE TITLE
Request to Add CONTRIBUTING.md File to the Project

### ISSUE THREAD

**Issue by martinyis** [martinyis/PrepAi#24]
I would like to request that we add a CONTRIBUTING.md file to our project. This file is essential for welcoming potential contributors and providing them with clear instructions on how to get started.

The CONTRIBUTING.md file should include the following points:

     1) Thank the person who is reading for their interest in contributing
     2) Tell them that we appreciate any issues they submit and they find on this project
     3) Before tackling the issue, ask to be assigned. Then, familiarize yourself with the project and files, read the issue statement 
         carefully, and don't hesitate to ask questions about the issue. Instructions on how to install the project on a local machine are 
         available in the README file.
     4) When submitting an issue, please provide the #id of the issue it fixes, a full description, and screenshots.

Adding this file will make it easier for potential contributors to get involved with our project. Thank you for considering this request.

**Comment by SamarendraGouda** [comment]
I would like to add CONTRIBUTING.md. Could you please assign me this issue?
