### ISSUE TITLE
Improve design of About section in HomePage

### ISSUE THREAD

**Issue by martinyis** [martinyis/PrepAi#29]
Description
The current design of the About section in HomePage could be improved. The component responsible for rendering this section is called About.jsx and can be found in the UI folder.

Task
We are looking for someone who can come up with creative ideas on how to make the About section look better. You are free to modify the About.jsx component in any way you see fit.

Goals
Improve the overall design of the About section in HomePage.
Make the section visually appealing and easy to read.
Enhance the user experience by providing relevant information in an engaging way.
Acceptance Criteria
The modified About.jsx component should be visually appealing and easy to read.
The modified component should be compatible with the existing codebase.
The modified component should enhance the user experience by providing relevant information in an engaging way.
Additional Information
If you have any questions or need further clarification, please do not hesitate to ask. Thank you for your contribution!
![image](https://user-images.githubusercontent.com/97173732/233164963-c2ec191c-4324-45c8-af55-04ef89cd4f88.png)

**Comment by k-deepak04** [comment]
@martinyis i can redesign this page please assign this to me

**Comment by k-deepak04** [comment]
#31 done 
Here are some key changes:

The background color has been changed to a lighter shade to make the text stand out more.
The font size has been increased and the line spacing has been reduced for improved readability.
The text is now left-aligned for easier reading.
A large, high-quality image has been added to make the page more visually appealing.
A new color palette has been used to make the page look more modern and cohesive.
Overall, these changes should make the About section more engaging and appealing to users while maintaining readability and usability.
new design
![image](https://user-images.githubusercontent.com/96341431/233177451-864426a0-6651-4866-a884-e8e68adb26f3.png)
