### ISSUE TITLE
Change border colors

### ISSUE THREAD

**Issue by martinyis** [martinyis/PrepAi#6]
All borders should look like in deisgn picture which you can find Starter design folder

**Comment by tyler-le** [comment]
i can do this

**Comment by KalebArmbrust** [comment]
Hey Martin, I'd love to contribute to the project. Can you assign this issue to me?

**Comment by martinyis** [comment]
> Hey Martin, I'd love to contribute to the project. Can you assign this issue to me?

Yup, go ahead. Ask me any questions if needed!

**Comment by KalebArmbrust** [comment]
Great, so just to clarify, are you wanting the Card's borders on the "create prep" tab to all be changed to a certain color? In the photo it looks like either the #7DD6FA or #64ABC7

**Comment by martinyis** [comment]
> Great, so just to clarify, are you wanting the Card's borders on the "create prep" tab to all be changed to a certain color? In the photo it looks like either the #7DD6FA or #64ABC7

Yes, they all have to be changed for #0f4f5f.

**Comment by KalebArmbrust** [comment]
Is this what you were hoping for? Wanted to confirm before I submit a pull request.

![Screenshot 2023-04-05 111041](https://user-images.githubusercontent.com/68127436/230140834-1c270326-c5ca-40ab-8550-6c0eebec807f.png)

**Comment by martinyis** [comment]
> Is this what you were hoping for? Wanted to confirm before I submit a pull request.
> 
> ![Screenshot 2023-04-05 111041](https://user-images.githubusercontent.com/68127436/230140834-1c270326-c5ca-40ab-8550-6c0eebec807f.png)
Looks good in the picture, did you make changes to the checkboxes as well?

**Comment by KalebArmbrust** [comment]
Yes, I changed the whole checkbox to look like the photo, because when I just tried to change the border I had to remove the default styling of the checkbox. Is that okay?

**Comment by martinyis** [comment]
> Yes, I changed the whole checkbox to look like the photo, because when I just tried to change the border I had to remove the default styling of the checkbox. Is that okay?

That is awesome! Waiting for your pr
