### ISSUE TITLE
Change color and font for links in Header

### ISSUE THREAD

**Issue by martinyis** [martinyis/PrepAi#7]
Description:

I would like to request a change in the color and font for links in the Header section of our website. Currently, the link color is not visually appealing and does not match our website's theme.

I propose that we change the link color to #86a9b5 and use the font specified in the theme.js file. This change will align the Header section with the overall website design and improve the user experience.

Please refer to the attached image for a visual representation of the proposed change.

![image](https://user-images.githubusercontent.com/97173732/230179474-a68cce7f-e2f1-485f-9209-d7ab3ba9a406.png)

**Comment by omernadeem1070** [comment]
Hello, I can take care of this. Thank you.

**Comment by martinyis** [comment]
> Hello, I can take care of this. Thank you.

Yes, assigning this to you. I am here if you have any questions.
