### ISSUE TITLE
Standardize font for text in CreatePrep.jsx file

### ISSUE THREAD

**Issue by martinyis** [martinyis/PrepAi#8]
I noticed that there are inconsistencies in the font used for text in the CreatePrep.jsx file. To ensure consistency and improve the visual appeal of the website, I propose that we standardize the font for all text in CreatePrep.jsx to "Cyntho Next".

This will require updating the CSS styles in the file to specify "Cyntho Next" as the font family for all text elements.

**Comment by anjalikesavarapu** [comment]
Hello @martinyis I would like to take up this. Please assign this to me.

**Comment by maazahmed408** [comment]
Hey , can you assign this task to me.

**Comment by martinyis** [comment]
Hey @maazahmed408 , Thank you for your interest. This issue is actually already closed. You can see more issues in issues tab

**Comment by maazahmed408** [comment]
okay thank you!
